---
title: "Grades Review"
author: "Cody Dailey"
date: "10/14/2020"
output: 
  html_document:
    code_folding: hide
runtime: shiny
---

<style type="text/css">
.main-container {
  max-width: 2500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


# Class Summary

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
# source("submissions_Compiler.R")

load("submissions.rdata")

```


```{r, message=FALSE, warning=FALSE, error=FALSE}
# source("./slack_discussion_tracking/slack_Reader.R")

# recent.slack.discussion.file <- list.files("slack_discussion_tracking", pattern = "slack_discussion_stats[0-9]+?.rdata", full.names = TRUE)[which.max(file.info(list.files("slack_discussion_tracking", pattern = "slack_discussion_stats[0-9]+?.rdata", full.names = TRUE))$ctime)] # using file.info()$ctime might fail with repo updating from github, all would have same ctime?
# load(recent.slack.discussion.file)
# load("slack_discussion_tracking/slack_discussion_stats20201016.rdata")



library(dplyr)

# previous.discussion.grades <- list.files(file.path("slack_discussion_tracking"), pattern = paste0("_grades"))
# dates <- as.Date(gsub(".*?_grades([0-9]+?)\\.rdata", "\\1", previous.discussion.grades), format="%Y%m%d")
# recent.discussion.grades <- previous.discussion.grades[which.max(dates)]
# load(file.path("slack_discussion_tracking", recent.discussion.grades))
load("./slack_discussion_tracking/discussion_grades20201206.rdata")



# previous.discussion.stats <- list.files(file.path("./slack_discussion_tracking"), pattern = paste0("slack_discussion_stats"))
# dates <- as.Date(gsub(".*?slack_discussion_stats([0-9]+?)\\.rdata", "\\1", previous.discussion.stats), format="%Y%m%d")
# recent.discussion.stats <- previous.discussion.stats[which.max(dates)]
# load(file.path("slack_discussion_tracking", recent.discussion.stats))
load("./slack_discussion_tracking/slack_discussion_stats20201206.rdata")

discussion.stats <- discussion.stats %>% mutate(module = gsub("(.*?)_discussions", "\\1", channel))

discussions <- full_join(discussion.grades, discussion.stats, by = c("email", "real.name", "module"))


discussions.summary <- discussions %>% group_by(email) %>% summarise(discussions.grade = round(mean(grade), 2))

```





```{r, message=FALSE, warning=FALSE, error=FALSE}

simple.grades <- submissions[, which(
  names(submissions)%in%c("lastname", "firstname", "email") | 
    grepl("grade", names(submissions)) | 
    grepl("\\.n\\.", names(submissions)) | 
    grepl("_duedate", names(submissions)))]

quizIDs <- gsub("_grade", "", names(simple.grades)[which(grepl("grade", names(simple.grades)))])


long.data <- list()

for(i in 1:length(quizIDs)){
  temp <- simple.grades[,c(1:3, which(grepl(quizIDs[i], names(simple.grades))))]
  
  if(ncol(temp)==5){
    temp[,6] <- c(NA)
    #temp[,7] <- c(NA)
  }
  
  names(temp)[4:6] <- c("grade", "n.questions", "n.correct")#"duedate", 
  temp$QuizID <- quizIDs[i]
  
  long.data[[i]] <- temp
}

```



```{r, message=FALSE, warning=FALSE, error=FALSE}
simple.grades <- bind_rows(long.data) #%>% filter(duedate<=Sys.Date())

grades.summary <- simple.grades %>% group_by(lastname, firstname, email) %>% 
  mutate(
    grade.zeros = ifelse(is.na(grade), 0, grade),
    n.questions = as.numeric(n.questions), 
    n.correct = as.numeric(n.correct)
    ) %>% 
  
  summarise(
    n.quizzes = n(), 
    n.submitted = sum(!is.na(grade)), 
    n.missing = sum(is.na(grade)), 
    grade = paste0(round(mean(grade.zeros), 2)), 
    n.questions = paste0("TOTQs = ", sum(n.questions, na.rm = TRUE)), 
    n.correct = paste0("TOTcorrect = ", sum(n.correct, na.rm = TRUE))
    ) %>% 
  
  ungroup() %>% 
  
  mutate(
    n.questions = paste0("TOTQs = ", max(as.numeric(gsub("[^0-9]{1-3}", "", n.questions)), na.rm=TRUE)),
    by.q.avg = round(100*as.numeric(gsub("[^0-9]{1-3}", "", n.correct))/as.numeric(gsub("[^0-9]{1-3}", "", n.questions)), 2)
    ) %>%
  
  left_join(discussions.summary, by = "email")




simple.grades <- simple.grades %>% mutate(grade = round(grade, 2)) %>% lapply(as.character) %>% bind_rows(grades.summary)
simple.grades <- simple.grades[order(simple.grades$lastname, simple.grades$firstname),]

# simple.grades[,1:13] <- lapply(simple.grades[,1:13], as.character)
simple.grades[,1:12] <- lapply(simple.grades[,1:12], as.character)

# simple.grades[nrow(simple.grades)+1,] <- list("LASTNAME", "FIRSTNAME", "EMAIL", "DUEDATE", "GRADE", "N.QUESTIONS", "N.CORRECT", "QUIZID", "N.QUIZZES", "N.SUBMITTED", "N.MISSING", "BY.Q.AVG", "DISCUSSIONS.GRADE")

simple.grades[nrow(simple.grades)+1,] <- list("LASTNAME", "FIRSTNAME", "EMAIL", "GRADE", "N.QUESTIONS", "N.CORRECT", "QUIZID", "N.QUIZZES", "N.SUBMITTED", "N.MISSING", "BY.Q.AVG", "DISCUSSIONS.GRADE")#"DUEDATE", 

```



## Grades From Classlist

```{r, message=FALSE, warning=FALSE, error=FALSE}


library(shiny)

ui <- shinyUI(
  fluidPage(
    verbatimTextOutput("Class Summary from Classlist"),
    DT::dataTableOutput("Class Summary by classlist")
  )
)

server <- shinyServer(function(input, output, session) {
  output$`Class Summary by classlist` <- DT::renderDataTable({
    return(DT::datatable(grades.summary[,names(grades.summary)[c(1:7, 11)]], class = "cell-border stripe", rownames = FALSE, filter = "top", extensions = "Buttons", options = list(dom = "Bfrtip", buttons = c("copy", "csv", "excel", "pdf", "print"), pageLength = 30)) )
  })
} 
)

shinyApp(ui = ui, server = server, options = list(height = 1500) )


```

## Grades From Submissions (Regraded by Question)

```{r}


ui <- shinyUI(
  fluidPage(
    verbatimTextOutput("Class Summary from Submissions"),
    DT::dataTableOutput("Class Summary by submissions")
  )
)

server <- shinyServer(function(input, output, session) {
    output$`Class Summary by submissions` <- DT::renderDataTable({
    return(DT::datatable(grades.summary[,names(grades.summary)[c(1:6,8:10)]], class = "cell-border stripe", rownames = FALSE, filter = "top", extensions = "Buttons", options = list(dom = "Bfrtip", buttons = c("copy", "csv", "excel", "pdf", "print"), pageLength = 30)) )
  })
} 
)


shinyApp(ui = ui, server = server, options = list(height = 1500) )

```




# Student Statistics


```{r, message=FALSE, warning=FALSE, error=FALSE}


ui <- shinyUI(
  fluidPage(
    selectInput("Student Email","Choose a student email to view grades.",
                choices = unique(simple.grades$email),
                selected = "EMAIL"),
    DT::dataTableOutput("Student Grades")
  )
)

server <- shinyServer(function(input, output, session) {
  # reactiveData <- reactive({
  #   return(simple.grades %>% filter(email == input$`Student Email`) %>% select(lastname, firstname, QuizID, duedate, grade, n.questions, n.correct, by.q.avg, n.quizzes, n.submitted, n.missing))  
  #   })
  reactiveData <- reactive({
    return(simple.grades %>% filter(email == input$`Student Email`) %>% select(lastname, firstname, QuizID, grade, n.questions, n.correct, by.q.avg, n.quizzes, n.submitted, n.missing))  
    })
  output$`Student Grades` <- DT::renderDataTable({
    return(DT::datatable(reactiveData(), class = "cell-border stripe", rownames = FALSE, filter = "top", extensions = "Buttons", options = list(dom = "Bfrtip", buttons = c("copy", "csv", "excel", "pdf", "print"), pageLength = 30)) )
  })
} 
)

shinyApp(ui = ui, server = server, options = list(height = 1500) )

```

## Discussion Posts




```{r}

ui <- shinyUI(
  fluidPage(
    DT::dataTableOutput("Discussion Statistics")
  )
)

server <- shinyServer(function(input, output, session) {
  output$`Discussion Statistics` <- DT::renderDataTable({
    return(DT::datatable(discussions, class = "cell-border stripe", rownames = FALSE, filter = "top", extensions = "Buttons", options = list(dom = "Bfrtip", buttons = c("copy", "csv", "excel", "pdf", "print"), pageLength = 30)) )
  })
} 
)

shinyApp(ui = ui, server = server, options = list(height = 1500) )



```









# Question Statistics

```{r, message=FALSE, warning=FALSE, error=FALSE}
questions <- submissions[,which(grepl("T[0-9]{1,2}R[0-9]{1,2}", names(submissions)) | grepl("TH[0-9]{1,2}M[0-9]{1,2}R[0-9]{1,2}", names(submissions)))]

questions.summary <- lapply(questions, function(x){return(list(Number.Correct = sum(x=="Correct", na.rm = TRUE), Number.Responses = sum(!is.na(x)),Percentage.Correct = round(sum(x=="Correct", na.rm = TRUE)/sum(!is.na(x))*100, 2)))})

questionID <- names(questions.summary)
quizID <- gsub("(.+?)\\..*", "\\1", questionID)

questions.summary <- bind_cols(quizID = quizID, questionID = questionID, bind_rows(questions.summary))
```



```{r, message=FALSE, warning=FALSE, error=FALSE}

ui <- shinyUI(
  fluidPage(
    selectInput("Quiz ID","Choose a Quiz ID to view a summary.",
                choices = c("ALL", unique(questions.summary$quizID)),
                selected = "ALL"),
    DT::dataTableOutput("Questions Summary")
  )
)

server <- shinyServer(function(input, output, session) {
  reactiveData <- reactive({
    if(input$`Quiz ID`=="ALL"){return(questions.summary)}else{return(subset(questions.summary, quizID == input$`Quiz ID`))}  
    })
  output$`Questions Summary` <- DT::renderDataTable({
    return(DT::datatable(reactiveData(), class = "cell-border stripe", rownames = FALSE, filter = "top", extensions = "Buttons", options = list(dom = "Bfrtip", buttons = c("copy", "csv", "excel", "pdf", "print"), pageLength = 30)) )
  })
} 
)

shinyApp(ui = ui, server = server, options = list(height = 1500) )

```
